import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {publicAudit} from '../scripts/audit.mjs';import {classifySearch,ownResource,checkCatalogs} from '../scripts/catalogs.mjs';import {boundedRequest} from '../scripts/lib/net.mjs';
import {response} from './support/fixture.mjs';
const cfg=JSON.parse(await readFile(new URL('../config/distribution.json',import.meta.url),'utf8'));
function server({drift=false,keyDrift=false,badMcp=false}={}){const calls=[];const fetcher=async(url,opts={})=>{const u=new URL(url);calls.push({path:u.pathname,opts});if(u.pathname==='/health')return response({status:'ok',source_sha256:drift?'other':cfg.expectedSourceSha256,payments:'live'});if(u.pathname==='/v1/capabilities')return response({deployment:'production',payment_mode:'live',native_services:[{capability:'rights.preflight.v1',enabled:true,payments_enabled:true,coverage:['https://example.com'],fresh_fee_micro:'20000',deep_fee_micro:'50000'}],features:{quote:false}});if(u.pathname==='/.well-known/acqpath-keys.json')return response({keys:[{jwk:{...cfg.publicEvidenceKey,x:keyDrift?'OTHER':cfg.publicEvidenceKey.x}}]});if(u.pathname==='/openapi.json')return response({paths:{'/v1/rights/quote':{}},components:{schemas:{RightsInput:{properties:{purpose:{enum:['ai-input']}}}}}});if(u.pathname==='/mcp'){const m=JSON.parse(opts.body);if(m.method==='initialize')return response({jsonrpc:'2.0',id:1,result:{protocolVersion:badMcp?'bad':cfg.mcp.protocolVersion}},200);if(m.method==='notifications/initialized')return response(null,202);if(m.method==='tools/list')return response({jsonrpc:'2.0',id:2,result:{tools:[{name:'acqpath_rights_quote',description:'quote only'}]}});throw Error('tool invocation not permitted');}return response({status:'ready'});};return {calls,fetcher};}
test('public audit passes mock native API and MCP handshake with no quotes/payments',async()=>{const f=server();const r=await publicAudit(cfg,{fetcher:f.fetcher});assert.equal(r.status,'PASS');assert.equal(r.noQuoteCreated,true);assert.ok(!f.calls.some(x=>x.path==='/v1/rights/quote'));});
test('source drift blocks publication readiness',async()=>{const r=await publicAudit(cfg,{fetcher:server({drift:true}).fetcher});assert.equal(r.status,'BLOCKED_OR_UNVERIFIED');});
test('remote key mismatch never silently changes the trusted key',async()=>{const r=await publicAudit(cfg,{fetcher:server({keyDrift:true}).fetcher});assert.equal(r.status,'BLOCKED_OR_UNVERIFIED');});
test('MCP protocol mismatch is reported, not ignored',async()=>{const r=await publicAudit(cfg,{fetcher:server({badMcp:true}).fetcher});assert.equal(r.status,'BLOCKED_OR_UNVERIFIED');});
test('network unavailability is not a false API regression or zero customers',async()=>{const r=await publicAudit(cfg,{fetcher:async()=>{throw Object.assign(Error('token should never be shown'),{code:'ENOTFOUND'});}});assert.equal(r.status,'BLOCKED_OR_UNVERIFIED');assert.equal(r.networkSummary.health.error,'ENOTFOUND');assert.ok(!JSON.stringify(r).includes('token should'));});
test('bounded HTTP rejects redirects without following',async()=>{let n=0;const r=await boundedRequest('https://example.com/',{allowedOrigins:['https://example.com']},async()=>{n++;return new Response(null,{status:302,headers:{location:'https://evil.example'}});});assert.equal(r.status,302);assert.equal(n,1);});
test('bounded HTTP rejects oversized payload',async()=>{await assert.rejects(boundedRequest('https://example.com/',{allowedOrigins:['https://example.com'],maxBytes:10},async()=>new Response('x'.repeat(11))),/RESPONSE_TOO_LARGE/);});
test('bounded HTTP rejects cross-origin destination and HTTP scheme',async()=>{await assert.rejects(boundedRequest('https://evil.example/',{allowedOrigins:['https://example.com']}));await assert.rejects(boundedRequest('http://example.com/',{allowedOrigins:['http://example.com']}));});
test('Bazaar auth failure remains AUTH_REQUIRED',()=>{assert.equal(classifySearch({status:401},cfg).state,'AUTH_REQUIRED');});
test('empty partial Bazaar result cannot prove absent listing',()=>{assert.equal(classifySearch({status:200,data:{resources:[],partialResults:true}},cfg).state,'NO_MATCH_IN_PARTIAL_RESULTS');});
test('listing matching brand only is not a merchant proof',()=>{assert.equal(ownResource({resource:'https://imposter.example/api',accepts:[{network:cfg.payment.network,asset:cfg.payment.asset,payTo:cfg.payment.payTo}]},cfg),false);});
test('valid merchant listing is found without claiming paid execution',()=>{const r=classifySearch({status:200,data:{resources:[{resource:cfg.apiOrigin+'/v1/rights/reports/:id',accepts:[{network:cfg.payment.network,asset:cfg.payment.asset,payTo:cfg.payment.payTo}]}]}},cfg);assert.equal(r.state,'FOUND');});
test('catalog query stops on 429 and still separately checks MCP registry',async()=>{let cdp=0;const r=await checkCatalogs(cfg,{fetcher:async url=>{if(new URL(url).host==='api.cdp.coinbase.com'){cdp++;return response({},429);}return response({servers:[]});}});assert.equal(cdp,1);assert.equal(r.mcpRegistry.state,'NO_MATCH_FOR_QUERY');});
test('registry requires exact namespace and endpoint',async()=>{const r=await checkCatalogs(cfg,{queries:[],fetcher:async url=>new URL(url).host==='registry.modelcontextprotocol.io'?response({servers:[{server:{name:cfg.mcp.name,version:cfg.mcp.version,remotes:[{url:cfg.mcp.url}]}}]}):response({resources:[]})});assert.equal(r.mcpRegistry.state,'FOUND');});
