import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,rm,writeFile,symlink,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {EncryptedCheckpointStore,buyOnce} from '../packages/rights-client/checkpoint-store.mjs';
const pass='test-only-passphrase-which-is-never-a-wallet-key';
async function directory(fn){const dir=await mkdtemp(join(tmpdir(),'acq-dist-test-'));try{return await fn(dir);}finally{await rm(dir,{recursive:true,force:true});}}
test('checkpoint encrypts, authenticates and reads data without plaintext secret',()=>directory(async dir=>{const store=new EncryptedCheckpointStore(dir,pass);await store.save('order',{claim_token:'hidden-test-value'});const raw=await readFile(store.path('order'),'utf8');assert.ok(!raw.includes('hidden-test-value'));assert.deepEqual(await store.load('order'),{claim_token:'hidden-test-value'});}));
test('wrong passphrase fails decryption',()=>directory(async dir=>{const a=new EncryptedCheckpointStore(dir,pass);await a.save('x',{a:1});await assert.rejects(new EncryptedCheckpointStore(dir,pass+'!').load('x'),/DECRYPTION_FAILED/);}));
test('ciphertext tamper fails closed',()=>directory(async dir=>{const a=new EncryptedCheckpointStore(dir,pass);await a.save('x',{a:1});const e=JSON.parse(await readFile(a.path('x'),'utf8'));e.tag='0'.repeat(32);await writeFile(a.path('x'),JSON.stringify(e));await assert.rejects(a.load('x'),/DECRYPTION_FAILED/);}));
test('checkpoint file cannot be moved to another purchase id',()=>directory(async dir=>{const a=new EncryptedCheckpointStore(dir,pass);await a.save('x',{a:1});await writeFile(a.path('y'),await readFile(a.path('x')));await assert.rejects(a.load('y'),/DECRYPTION_FAILED/);}));
test('short passwords and traversal ids rejected',()=>{assert.throws(()=>new EncryptedCheckpointStore('/tmp','short'));const s=new EncryptedCheckpointStore('/tmp',pass);assert.throws(()=>s.path('../outside'));});
test('concurrent same-order lock cannot be acquired',()=>directory(async dir=>{const a=new EncryptedCheckpointStore(dir,pass);await a.withLock('x',async()=>{await assert.rejects(a.withLock('x',async()=>{}),/LOCKED/);});}));
test('starting marker after interrupted acquisition cannot create a second purchase',()=>directory(async dir=>{const s=new EncryptedCheckpointStore(dir,pass);await s.save('x',{kind:'starting',input:{a:1}});await assert.rejects(buyOnce({buy:()=>{throw Error('should not buy');}},{a:1},{store:s,id:'x'}),/REVIEW_REQUIRED/);}));
test('logical purchase id resumes, never calls buy twice',()=>directory(async dir=>{const s=new EncryptedCheckpointStore(dir,pass);let buys=0,resumes=0;const input={a:1};const client={buy:async(i,{onCheckpoint})=>{buys++;await onCheckpoint({input:i,completed:false});return {status:'DELIVERED'};},resume:async()=>{resumes++;return {status:'DELIVERED'};}};await buyOnce(client,input,{store:s,id:'x'});await buyOnce(client,input,{store:s,id:'x'});assert.equal(buys,1);assert.equal(resumes,1);await assert.rejects(buyOnce(client,{a:2},{store:s,id:'x'}),/DIFFERENT_INPUT/);}));
test('unavailable result is terminal for the same logical order id',()=>directory(async dir=>{const s=new EncryptedCheckpointStore(dir,pass);let calls=0;const client={buy:async()=>{calls++;return {status:'UNAVAILABLE'};}};await buyOnce(client,{a:1},{store:s,id:'x'});await buyOnce(client,{a:1},{store:s,id:'x'});assert.equal(calls,1);}));
test('symlink or Windows junction checkpoint directory is rejected',()=>directory(async dir=>{const outside=join(dir,'outside'),link=join(dir,'linked');await mkdir(outside);await symlink(outside,link,process.platform==='win32'?'junction':'dir');await assert.rejects(new EncryptedCheckpointStore(link,pass).save('x',{a:1}),/SYMLINK/);}));
