import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {ROOT} from '../scripts/lib/io.mjs';
import {normalizeAnalytics,fetchPublicFile,publicAssetPath,localLinks,securityHeadersMatch} from '../scripts/verify-docs.mjs';
import {contractDrift,registryMatches,readRegistry} from '../scripts/discovery-check.mjs';
test('edge normalization preserves unknown scripts and detects duplicate approved insertion',()=>{const snippet='<script src="https://static.cloudflareinsights.com/beacon.min.js"></script>';const original='<body>Expected</body>';assert.equal(normalizeAnalytics(Buffer.from(original+snippet),snippet).bytes.toString(),original);assert.equal(normalizeAnalytics(Buffer.from(original+'<script>unknown()</script>'),snippet).bytes.toString(),original+'<script>unknown()</script>');assert.throws(()=>normalizeAnalytics(Buffer.from(snippet+snippet),snippet),/DUPLICATE/);});
test('public readback refuses cross-origin redirects and oversized streaming bodies',async()=>{await assert.rejects(fetchPublicFile('https://developers.getacqpath.com/',{fetcher:async()=>new Response('',{status:302,headers:{location:'https://untrusted.example/'}})}),/UNEXPECTED_PUBLIC_ORIGIN/);await assert.rejects(fetchPublicFile('https://developers.getacqpath.com/',{maxBytes:2,fetcher:async()=>new Response('large')}),/TOO_LARGE/);for(const path of ['../secret','/absolute','a//b','a?b'])assert.throws(()=>publicAssetPath(path));});
test('broken local links cannot be hidden by extensionless canonical paths',()=>{assert.deepEqual(localLinks('<a href="/quickstart">Go</a><link href="/style.css"><a href="/missing#here">Missing</a>','https://developers.getacqpath.com'),['/quickstart','/style.css','/missing']);});
test('stricter text CSP needs no analytics permission while HTML still requires it',()=>{const h=new Headers({'x-content-type-options':'nosniff','x-frame-options':'DENY','content-security-policy':"default-src 'none'; frame-ancestors 'none'"});assert.equal(securityHeadersMatch(h,false),true);assert.equal(securityHeadersMatch(h,true),false);h.delete('x-content-type-options');assert.equal(securityHeadersMatch(h,false),false);});
test('discovery detects price, coverage and provider-routing drift',async()=>{const c=JSON.parse(await readFile(join(ROOT,'metadata/public-contract.json'),'utf8')),s=c.capabilities.native_services[0];const o={coverage:s.coverage,freshFeeMicro:s.fresh_fee_micro,deepFeeMicro:s.deep_fee_micro,paidPurposes:['ai-input','ai-index','ai-train','search'],providerRouting:false};assert.equal(contractDrift(o,c),false);for(const change of [{freshFeeMicro:'30000'},{coverage:[]},{providerRouting:true},{paidPurposes:['crawl']}])assert.equal(contractDrift({...o,...change},c),true);});
test('registry acceptance requires exact current metadata and active lifecycle',()=>{const server={name:'com.getacqpath/acqpath',description:'Expected',version:'1'};const record={server,_meta:{'io.modelcontextprotocol.registry/official':{status:'active'}}};assert.equal(registryMatches(record,server),true);assert.equal(registryMatches({...record,server:{...server,description:'Stale'}},server),false);assert.equal(registryMatches({server},server),false);});

test('registry retries a transient public GET once and exposes the attempt count',async()=>{let n=0;const r=await readRegistry('https://registry.modelcontextprotocol.io/v0.1/servers?search=AcqPath',async()=>{if(++n===1)throw new DOMException('timeout','AbortError');return new Response(JSON.stringify({servers:[]}),{headers:{'content-type':'application/json'}});});assert.equal(n,2);assert.equal(r.attempts,2);assert.deepEqual(r.data,{servers:[]});});
test('registry retries are bounded and never retry unsafe destinations or metadata rejection',async()=>{let n=0;await assert.rejects(readRegistry('https://registry.modelcontextprotocol.io/v0.1/servers',async()=>{n++;throw new DOMException('timeout','AbortError');}),{code:'REGISTRY_TIMEOUT'});assert.equal(n,2);n=0;await assert.rejects(readRegistry('https://untrusted.example/',async()=>{n++;return new Response('{}');}),/NETWORK_DESTINATION_REJECTED/);assert.equal(n,0);const r=await readRegistry('https://registry.modelcontextprotocol.io/v0.1/servers',async()=>{n++;return new Response('{}',{status:404});});assert.equal(r.status,404);assert.equal(n,1);});
