import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,cp,readFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {ROOT} from '../scripts/lib/io.mjs';
import {build} from '../scripts/build.mjs';
import {renderPage,pagePath} from '../scripts/site.mjs';
import {createEvidenceGate,requiresHold} from '../examples/evidence-gate.mjs';
import {fixture,input} from './support/fixture.mjs';

const supported={enabled:true,payments_enabled:true,coverage:['https://example.com'],fresh_fee_micro:'20000',deep_fee_micro:'50000',capability:'rights.preflight.v1'};
async function gateFixture(){const f=await fixture();f.client.capabilities=async()=>({native_services:[supported]});let saved=null;const store={load:async()=>saved,save:async(_id,value)=>{saved=structuredClone(value);await f.onCheckpoint(value);},withLock:async(_id,fn)=>fn()};return {f,gate:createEvidenceGate({client:f.client,store}),request:{id:'one-job',resource:input.resource,purpose:input.purpose},store};}
test('ingestion gate refuses unsupported origins before creating a quote',async()=>{const {f,gate,request}=await gateFixture();const r=await gate({...request,resource:'https://unsupported.example/'});assert.equal(r.status,'OUTSIDE_SUPPORTED_SCOPE');assert.equal(f.counts.quoteCalls,0);assert.equal(f.counts.signerCalls,0);});
test('ingestion gate does not silently accept a price increase',async()=>{const {f,gate,request}=await gateFixture();f.client.capabilities=async()=>({native_services:[{...supported,fresh_fee_micro:'21000'}]});assert.equal((await gate(request)).status,'PRICE_REQUIRES_REVIEW');assert.equal(f.counts.quoteCalls,0);});
test('verified delivery is evidence and never automatic ingestion permission',async()=>{const {gate,request}=await gateFixture();const r=await gate(request);assert.equal(r.status,'DELIVERED');assert.equal(r.decision,'ALLOW_DECLARED');assert.equal(r.receipt_verified,true);assert.equal(r.ingestionAuthorized,false);assert.equal(r.independent_chain_validation,false);assert.equal('quote' in r,false);});
test('ambiguous purchase resumes the same authorization even if coverage changes',async()=>{const {f,gate,request}=await gateFixture();f.control.failSubmit=true;await assert.rejects(gate(request),/INJECTED_NETWORK_LOSS/);f.control.failSubmit=false;f.client.capabilities=async()=>{throw Error('COVERAGE_MUST_NOT_BLOCK_RECOVERY');};const r=await gate(request);assert.equal(r.status,'DELIVERED');assert.equal(f.counts.quoteCalls,1);assert.equal(f.counts.signerCalls,1);assert.equal(f.counts.submissions,2);});
test('unknown, unsupported and license-required outcomes hold ingestion',()=>{for(const s of ['UNKNOWN','DENY_DECLARED','LICENSE_REQUIRED',undefined,'OUTSIDE_SUPPORTED_SCOPE'])assert.equal(requiresHold(s),true);});
test('documentation rejects unsafe page paths and escapes publisher text',async()=>{assert.throws(()=>pagePath('../escape'));const cfg=JSON.parse(await readFile(join(ROOT,'config/distribution.json'),'utf8'));const c=JSON.parse(await readFile(join(ROOT,'metadata/public-contract.json'),'utf8'));const p={slug:'index',title:'<script>bad</script>',description:'" onload="bad',sections:[]};const html=renderPage(p,[p],cfg,c);assert.ok(!html.includes('<script>bad'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(html.includes('rel="canonical"'));assert.throws(()=>renderPage({...p,sections:[{title:'Bad',paragraphs:[],links:[{label:'bad',href:'javascript:alert(1)'}]}]},[p],cfg,c),/UNSAFE_DOCUMENTATION_LINK/);});
test('machine discovery assets match the real paid-purpose contract and exclude a paid crawl tool',async()=>{const d=await mkdtemp(join(tmpdir(),'acq-discovery-'));try{for(const p of ['config','metadata','packages','site','skills','examples'])await cp(join(ROOT,p),join(d,p),{recursive:true});await build(d);const read=async p=>JSON.parse(await readFile(join(d,'out/site',p),'utf8'));const spec=await read('openapi.json'),profile=await read('.well-known/acqpath-distribution.json'),tools=await read('mcp-tools.json');assert.deepEqual(profile.supportedPurposes,spec.components.schemas.RightsInput.properties.purpose.enum);assert.equal(profile.limitations.paidCrawl,false);assert.ok(!tools.tools.some(t=>t.name==='acqpath_quote'));assert.ok(spec.paths['/v1/rights/reports/{id}'].get.parameters.some(p=>p.name==='X-AcqPath-Claim'&&p.required));const sitemap=await readFile(join(d,'out/site/sitemap.xml'),'utf8');assert.ok(sitemap.includes('/rag-ingestion'));assert.ok(!sitemap.includes('/from-'));const full=await readFile(join(d,'out/site/llms-full.txt'),'utf8');assert.ok(full.includes('UNKNOWN'));assert.ok(full.includes('same checkpoint'));}finally{await rm(d,{recursive:true,force:true});}});
