import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,cp,readFile,writeFile,mkdir,rm,access} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {ROOT,workspace,inside,writeLocal,redact} from '../scripts/lib/io.mjs';import {allowedTracked} from '../scripts/git-publish.mjs';import {metricSummary} from '../scripts/metrics.mjs';import {localAllowed} from '../scripts/buyer-demo.mjs';import {run} from '../scripts/lib/process.mjs';import {secretFindings} from '../scripts/verify.mjs';import {build} from '../scripts/build.mjs';import {recentAudit,publishNpm} from '../scripts/publish.mjs';
async function temp(fn){const d=await mkdtemp(join(tmpdir(),'acq-dist-fixture-'));try{return await fn(d);}finally{await rm(d,{force:true,recursive:true});}}
test('writes cannot escape distribution workspace',()=>temp(async d=>{await assert.rejects(writeLocal('../outside','test',d),/OUTSIDE/);assert.equal(inside(d,join(d,'safe')),true);}));
test('workspace nested under core repository is rejected',()=>temp(async d=>{await mkdir(join(d,'src'));await mkdir(join(d,'config'));await writeFile(join(d,'src/worker.mjs'),'');await writeFile(join(d,'config/operator.json'),'{}');await mkdir(join(d,'nested'));await writeFile(join(d,'nested/.acqpath-distribution-root'),'acqpath-distribution-v1');await assert.rejects(workspace(join(d,'nested')),/OUTSIDE_CORE/);}));
test('Git publisher refuses secret and private checkpoint file names',()=>{for(const p of ['.npmrc','.git-credentials','config/revenue.json','.private/a','out/rights-client/a','.local/test','keys/a.pem','a/production-operator-token.txt','.env','a/file.json.enc'])assert.equal(allowedTracked(p),false,p);assert.equal(allowedTracked('packages/rights-client/index.mjs'),true);});
test('redaction removes secret data but retains operational counts',()=>{const r=redact({claim_token:'hidden',count:3,nested:{Authorization:'Bearer hidden'}});assert.equal(r.claim_token,'[REDACTED]');assert.equal(r.count,3);assert.ok(!JSON.stringify(r).includes('Bearer hidden'));});
test('secret pattern scanner detects generated private-key material',()=>{assert.ok(secretFindings('x.txt','-----BEGIN '+'PRIVATE KEY-----').includes('PEM_PRIVATE'));assert.ok(secretFindings('x.txt','ghp_'+'X'.repeat(40)).includes('GITHUB_TOKEN'));});
test('aggregate revenue excludes testnet and does not fabricate organic revenue or profit',()=>{const r=metricSummary({quotes:5,metadata_fetches:7,payments:[{network:'eip155:8453',paid_reports:2,payer_identifiers:1,received_micro:'40000'},{network:'eip155:84532',paid_reports:10,payer_identifiers:5,received_micro:'999999'}],repeats:[{network:'eip155:8453',repeat_payer_identifiers:1}]});assert.equal(r.mainnetReceivedMicro,'40000');assert.equal(r.organicRevenueMicro,null);assert.equal(r.netProfitMicro,null);assert.equal(r.externalPayersVerified,false);});
test('negative or imprecise business counters rejected',()=>{assert.throws(()=>metricSummary({quotes:-1,metadata_fetches:0,payments:[],repeats:[]}));assert.throws(()=>metricSummary({quotes:0,metadata_fetches:0,payments:[{network:'eip155:8453',received_micro:'1.2',paid_reports:1,payer_identifiers:1}],repeats:[]}));});
test('loopback purchase UI requires exact host, origin and token',()=>{const headers={host:'127.0.0.1:1111',origin:'http://127.0.0.1:1111','content-type':'application/json','x-acq-local':'abc'};assert.equal(localAllowed({headers},headers.host,headers.origin,'abc'),true);assert.equal(localAllowed({headers:{...headers,origin:'https://evil.example'}},headers.host,headers.origin,'abc'),false);assert.equal(localAllowed({headers:{...headers,'x-acq-local':'wrong'}},headers.host,headers.origin,'abc'),false);});
test('subprocess errors are reported and no implicit shell is used',async()=>{const r=await run(process.execPath,['-e','process.stdout.write("ok");process.exit(7)'],{cwd:ROOT});assert.equal(r.code,7);assert.equal(r.stdout,'ok');});
test('subprocess has bounded timeout',async()=>{await assert.rejects(run(process.execPath,['-e','setTimeout(()=>{},5000)'],{cwd:ROOT,timeoutMs:50}),/TIMEOUT/);});
test('publishing refuses stale or failed public readiness',()=>temp(async d=>{await mkdir(join(d,'config'));await mkdir(join(d,'.local'));await cp(join(ROOT,'config/distribution.json'),join(d,'config/distribution.json'));await writeFile(join(d,'.local/public-audit.json'),JSON.stringify({status:'PASS',at:'2020-01-01T00:00:00Z'}));await assert.rejects(recentAudit(d),/FRESH_PUBLIC/);}));
test('static build removes stale output and exports only allowlisted public files',()=>temp(async d=>{for(const name of ['config','metadata','site','packages','examples','skills'])await cp(join(ROOT,name),join(d,name),{recursive:true});await mkdir(join(d,'out/site'),{recursive:true});await writeFile(join(d,'out/site/secret.txt'),'never copy');const cfg=JSON.parse(await readFile(join(d,'config/distribution.json'),'utf8'));cfg.publication.npmLicenseApproved=false;await writeFile(join(d,'config/distribution.json'),JSON.stringify(cfg));await build(d);await assert.rejects(access(join(d,'out/site/secret.txt')));const h=await readFile(join(d,'out/site/index.html'),'utf8');assert.ok(h.includes('legal clearance'));const pkg=JSON.parse(await readFile(join(d,'out/rights-client/package.json'),'utf8'));assert.equal(pkg.private,true);assert.equal(pkg.license,'UNLICENSED');}));

import {validateManifest} from '../scripts/manifest.mjs';
import {github} from '../scripts/lib/github.mjs';
test('owner publication hold keeps the MIT client private and blocks the publisher',()=>temp(async d=>{for(const name of ['config','metadata','site','packages','examples','skills'])await cp(join(ROOT,name),join(d,name),{recursive:true});const cfg=JSON.parse(await readFile(join(d,'config/distribution.json'),'utf8'));cfg.publication.npmLicenseApproved=true;cfg.publication.npmPublicationEnabled=false;await writeFile(join(d,'config/distribution.json'),JSON.stringify(cfg));await build(d);const pkg=JSON.parse(await readFile(join(d,'out/rights-client/package.json'),'utf8'));assert.equal(pkg.private,true);assert.equal(pkg.license,'MIT');await assert.rejects(publishNpm(d),/NPM_PUBLICATION_DISABLED_BY_OWNER/);}));
test('Git publication excludes nested tooling credentials and archives',()=>{for(const p of ['.wrangler/config.json','nested/.private/key.json','nested/.tools/token.json','backup.zip','source.tar.gz','client.tgz'])assert.equal(allowedTracked(p),false,p);});
test('workspace GitHub CLI rejects a tampered binary before execution',()=>temp(async d=>{await mkdir(join(d,'.tools/gh/bin'),{recursive:true});await writeFile(join(d,'.tools/gh/bin/gh.exe'),'not executable');await writeFile(join(d,'.tools/gh.lock.json'),JSON.stringify({repository:'cli/cli',binarySha256:'0'.repeat(64)}));await assert.rejects(github(['version'],{root:d}),/INTEGRITY_MISMATCH/);}));
test('explicit owner approval produces the public MIT client package',()=>temp(async d=>{for(const name of ['config','metadata','site','packages','examples','skills'])await cp(join(ROOT,name),join(d,name),{recursive:true});const cfg=JSON.parse(await readFile(join(d,'config/distribution.json'),'utf8'));cfg.publication.npmLicenseApproved=true;cfg.publication.npmPublicationEnabled=true;await writeFile(join(d,'config/distribution.json'),JSON.stringify(cfg));await build(d);const pkg=JSON.parse(await readFile(join(d,'out/rights-client/package.json'),'utf8'));assert.equal(pkg.private,false);assert.equal(pkg.license,'MIT');assert.equal(pkg.name,cfg.publication.npmName);await assert.rejects(access(join(d,'out/site/_worker.js')));const headers=await readFile(join(d,'out/site/_headers'),'utf8');assert.ok(headers.includes("default-src 'none'"));}));
test('Registry manifest respects the 100-character description and fixed remote profile',async()=>{const m=JSON.parse(await readFile(join(ROOT,'metadata/server.json'),'utf8'));assert.equal(validateManifest(m).name,'com.getacqpath/acqpath');assert.throws(()=>validateManifest({...m,description:'x'.repeat(101)}));});
test('Registry manifest may not include private claim headers',async()=>{const m=JSON.parse(await readFile(join(ROOT,'metadata/server.json'),'utf8'));m.remotes[0].headers=[{name:'X-AcqPath-Claim'}];assert.throws(()=>validateManifest(m));});
