import {join} from 'node:path';
import {copyFile,readFile} from 'node:fs/promises';
import {ROOT,load,writeLocal} from './lib/io.mjs';
import {pagePath} from './site.mjs';
export const exampleFiles=['README.md','read-only.mjs','read-only.py','evidence-gate.mjs','workflows.ts'];
export async function discoveryAssets(cfg,pages,root=ROOT){
 const contract=await load(join(root,'metadata/public-contract.json')),examples=await load(join(root,'metadata/examples.json'));
 const base=cfg.publication.docsUrl,native=contract.capabilities.native_services.find(s=>s.capability==='rights.preflight.v1');
 const emit=(path,value)=>writeLocal('out/site/'+path,value,root);
 const pricing={schema:'acqpath.pricing-snapshot.v1',observedAt:contract.observedAt,currency:'USDC',unit:'prepared rights report',network:cfg.payment.network,fresh:{micro:native.fresh_fee_micro,decimal:(Number(native.fresh_fee_micro)/1e6).toFixed(2)},deep:{micro:native.deep_fee_micro,decimal:(Number(native.deep_fee_micro)/1e6).toFixed(2)},liveSource:cfg.apiOrigin+'/v1/capabilities',paymentAuthority:'The verified signed quote; this snapshot does not authorize payment',notALicense:true};
 const service={'@context':'https://schema.org','@type':'SoftwareApplication',name:'AcqPath Rights Preflight',applicationCategory:'DeveloperApplication',operatingSystem:'Any platform with HTTPS',url:base,description:'Check observed RSL declarations before AI input, RAG indexing, training or search. Buy signed rights evidence using bounded HTTP x402 payments. Not a license or legal clearance.',featureList:['Observed RSL declaration evidence','Explicit supported-origin coverage','AI input, indexing, training and search purposes','Ed25519 report, receipt and delivery binding','MCP discovery and quote preparation','HTTP x402 v2 exact paid report delivery'],sameAs:['https://github.com/reflectme-source/acqpath-distribution','https://registry.modelcontextprotocol.io/v0.1/servers/'+encodeURIComponent(cfg.mcp.name)+'/versions/'+cfg.mcp.version],documentation:base+'/quickstart'};
 const discovery={schema:'acqpath.distribution.discovery.v1',observedAt:contract.observedAt,apiOrigin:cfg.apiOrigin,documentation:base,serviceMetadata:base+'/service.json',openapi:base+'/openapi.json',liveOpenapi:contract.liveOpenapi,mcp:{url:cfg.mcp.url,transport:'streamable-http',protocolVersion:cfg.mcp.protocolVersion,registryName:cfg.mcp.name,registryVersion:cfg.mcp.version,remoteCoreVersion:contract.coreVersion,paidDelivery:'HTTP x402 outside MCP',recommendedTools:contract.tools.map(t=>t.name),disabledTools:contract.disabledTools},pricing:base+'/pricing.json',capabilities:base+'/capabilities.json',examples:base+'/examples.json',skill:base+'/SKILL.md',llms:base+'/llms.txt',supportedPurposes:['ai-input','ai-train','ai-index','search'],coverage:native.coverage,limitations:{legalClearance:false,ownershipVerification:false,licenseAcquisition:false,paidCrawl:false,providerRouting:false,mainnetTested:false,paymentAttribution:false},retry:'Persist encrypted checkpoint before submission; resume exact authorization after ambiguity'};
 await emit('icon.svg',await readFile(join(root,'site/icon.svg'),'utf8'));
 await emit('service.json',service);await emit('pricing.json',pricing);await emit('capabilities.json',{...contract.capabilities,'x-distribution-observed-at':contract.observedAt,'x-live-source':cfg.apiOrigin+'/v1/capabilities'});
 await emit('.well-known/acqpath-distribution.json',discovery);await emit('examples.json',examples);await emit('examples/workflow.json',examples.workflow);
 await emit('mcp-config.json',examples.mcp.generic);await emit('vscode-mcp.json',examples.mcp.vscode);
 await emit('mcp-tools.json',{schema:'acqpath.documented-mcp-tools.v1',observedAt:contract.observedAt,metadataRole:'Documentation overlay; does not modify the remote tools/list response',endpoint:cfg.mcp.url,serverInfo:contract.serverInfo,tools:contract.tools.map(t=>({...t,documentationDescription:t.name==='acqpath_capabilities'?'Read current RSL report availability, origin coverage and prices before AI/RAG integration. No payment.':'Prepare one bounded RSL declaration report quote before AI input, indexing, training or search. This can fetch metadata and consumes quota; it performs no settlement. Keep its claim private.'})),disabledTools:contract.disabledTools});
 await copyFile(join(root,'metadata/openapi.public.json'),join(root,'out/site/openapi.json'));
 await emit('intents.json',await load(join(root,'metadata/intents.json')));
 const skill=await readFile(join(root,'skills/acqpath-rights-preflight/SKILL.md'),'utf8');await emit('SKILL.md',skill);
 let llms='# AcqPath — RSL rights preflight\n\n> Observed declaration evidence before AI input, RAG indexing, training or search. Reports are not licenses or legal clearance.\n\nMCP: '+cfg.mcp.url+' (Streamable HTTP). Paid report delivery uses HTTP x402 outside MCP.\nFresh '+pricing.fresh.decimal+' USDC; deep '+pricing.deep.decimal+' USDC, observed '+contract.observedAt+'. Verify live capabilities and signed quote.\nUNKNOWN and unsupported inputs do not authorize ingestion. Private claims and signatures stay outside model context. npm is unpublished.\n\n## Integration\n';
 for(const p of pages.filter(p=>!p.canonical))llms+='- ['+p.title+']('+base+pagePath(p.slug)+'): '+p.description+'\n';
 llms+='\n## Machine-readable assets\n';for(const [label,path]of [['Agent skill','SKILL.md'],['OpenAPI subset','openapi.json'],['Service metadata','service.json'],['Discovery profile','.well-known/acqpath-distribution.json'],['Capabilities snapshot','capabilities.json'],['Pricing snapshot','pricing.json'],['MCP configuration','mcp-config.json'],['Input examples','examples.json'],['Documented tools','mcp-tools.json'],['Full reference','llms-full.txt']])llms+='- ['+label+']('+base+'/'+path+')\n';
 await emit('llms.txt',llms);
 const full=llms+'\n## Full integration reference\n\n'+pages.filter(p=>!p.canonical).map(p=>'# '+p.title+'\nCanonical: '+base+pagePath(p.slug)+'\n\n'+p.description+'\n\n'+p.sections.map(s=>'## '+s.title+'\n\n'+s.paragraphs.join('\n\n')+(s.code?'\n\n```text\n'+s.code+'\n```':'')+(s.links?'\n\n'+s.links.map(l=>'- ['+l.label+']('+(l.href.startsWith('/')?base+l.href:l.href)+')').join('\n'):'')).join('\n\n')).join('\n\n');await emit('llms-full.txt',full);
 for(const name of exampleFiles)await emit('examples/'+name,await readFile(join(root,'examples',name),'utf8'));
 await emit('discovery-assets.json',{schema:'acqpath.public-assets.v1',files:['icon.svg','service.json','pricing.json','capabilities.json','.well-known/acqpath-distribution.json','examples.json','examples/workflow.json','mcp-config.json','vscode-mcp.json','mcp-tools.json','openapi.json','intents.json','SKILL.md','llms.txt','llms-full.txt',...exampleFiles.map(f=>'examples/'+f)]});
 return contract;
}
