export const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function pagePath(slug){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))throw Error('INVALID_PAGE_SLUG');return slug==='index'?'/':'/'+slug;}
function safeLink(href){if(typeof href!=='string'||!(href.startsWith('/')&&!href.startsWith('//')||/^https:\/\//.test(href)))throw Error('UNSAFE_DOCUMENTATION_LINK');return escapeHtml(href);}
export function renderPage(page,pages,cfg,contract,styleVersion="local"){
 const e=escapeHtml,base=cfg.publication.docsUrl,canonical=base+pagePath(page.canonical||page.slug);
 const native=contract.capabilities.native_services.find(s=>s.capability==='rights.preflight.v1');
 const nav=pages.filter(p=>p.nav!==false&&['index','gateway','quickstart','connect','integrations','pricing','recovery'].includes(p.slug)).map(p=>`<a${p.slug===page.slug?' aria-current="page"':''} href="${pagePath(p.slug)}">${e(p.label)}</a>`).join('');
 const section=s=>`<section><h2>${e(s.title)}</h2>${s.paragraphs.map(t=>`<p>${e(t)}</p>`).join('')}${s.code?`<pre tabindex="0"><code>${e(s.code)}</code></pre>`:''}${s.links?`<div class="links">${s.links.map(l=>`<a href="${safeLink(l.href)}">${e(l.label)} <span aria-hidden="true">↗</span></a>`).join('')}</div>`:''}</section>`;
 const hero=page.hero?`<div class="actions"><a class="primary" href="/quickstart">Integrate rights preflight <span aria-hidden="true">→</span></a><a class="secondary" href="/connect">Connect MCP</a></div><div class="facts"><div><span>Fresh report</span><strong>${e((Number(native.fresh_fee_micro)/1e6).toFixed(2))} USDC</strong></div><div><span>Deep report</span><strong>${e((Number(native.deep_fee_micro)/1e6).toFixed(2))} USDC</strong></div><div><span>Returns</span><strong>Signed declaration evidence</strong></div></div><p class="scope-note">Four observed origins · ai-input / ai-index / ai-train / search · UNKNOWN means hold.<br>Prices and coverage observed ${e(contract.observedAt.slice(0,10))}; verify the live quote. Reports are not licenses or legal clearance.</p>`:'';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${e(page.description)}"><meta name="referrer" content="no-referrer"><title>${e(page.title)} | AcqPath</title><link rel="canonical" href="${e(canonical)}"><meta property="og:type" content="website"><meta property="og:title" content="${e(page.title)}"><meta property="og:description" content="${e(page.description)}"><meta property="og:url" content="${e(canonical)}"><meta name="twitter:card" content="summary"><link rel="alternate" type="application/ld+json" href="/service.json" title="Service metadata"><link rel="alternate" type="text/plain" href="/llms.txt" title="Machine-readable documentation"><link rel="stylesheet" href="/style.css?v=${e(styleVersion)}"></head><body><a class="skip" href="#content">Skip to content</a><header><a class="brand" href="/">AcqPath <span>Rights Gateway</span></a><nav aria-label="Main">${nav}</nav></header><main id="content"><div class="intro"><p class="eyebrow">RSL DECLARATIONS · SIGNED EVIDENCE · HTTP X402</p><h1>${e(page.title)}</h1><p class="lead">${e(page.description)}</p>${hero}</div>${page.sections.map(section).join('')}<aside>Use observed declarations as evidence for your own policy. AcqPath does not verify ownership, grant permission or acquire licenses. Keep claims, signatures and checkpoints outside model prompts.</aside></main><footer><div><a href="https://getacqpath.com">Product</a> · <a href="https://github.com/reflectme-source/acqpath-distribution">GitHub</a> · <a href="/openapi.json">OpenAPI</a> · <a href="/SKILL.md">Agent skill</a> · <a href="/llms-full.txt">Full machine docs</a> · <a href="/service.json">Service metadata</a></div><p>Browser analytics may measure documentation usage. It does not attribute API payments or identify autonomous agents.</p></footer></body></html>`;
}
